Today i was trying CNN image processing file. Unfotunately i left the Jupyter notebook open and next day afternoon, i tried to resume the notebook
and was surprised to get the below error : 

Error 1: AttributeError: module 'pandas' has no attribute 'core'

I have never faced this error and was literaly shell shocked..As i have not faced this before , i went into introspection mode..i discovered this:

Root cause:Jupyter notebook idle.

Fix : Just restart and voila,this issue fixed by itself.
